apiVersion: apps/v1
kind: Deployment
metadata:
  name: flashcards-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flashcards
  template:
    metadata:
      labels:
        app: flashcards
    spec:
      containers:
        - name: app
          image: app:local
          ports:
            - containerPort: 8000
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          env:
            - name: APP_ENV
              value: "dev"
